name: Setup
description: Setup action

runs:
  using: composite
  steps:
    # install tools
    - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1

    # install dependencies
    - uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: ${{ runner.os }}-bun-
    - run: bun install --frozen-lockfile
      shell: bash
